spring:
  redis:
    port: 6379
    host: localhost
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/purity?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&ServerTimezone=UTC
    username: root
    password: 12345678
  security:
    user:
      name: admin
      password: 12345678
