# spring config
spring:
  redis:
    port: 6379
    host: localhost
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&ServerTimezone=UTC
    username: root
    password: 12345678
  security:
    user:
      name: admin
      password: 12345678

# mybatis配置
mybatis:
  type-aliases-package: com.example.demo.model
#  config-location: classpath:db/mybatis/mybatis-config.xml

# mybatis分页插件
pagehelper:
  #  dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

env:
  uploadFilePath: D:\uploadFiles
  exportFilePath: D:\exportFiles
  uploadFolder: /uploadFiles/
  exportFolder: /exportFiles/
